### ISSUE TITLE
Ошибка при docker-compose up

### ISSUE THREAD

**Issue by Abdujabbor** [TheArdent/Laravel-Skeleton#6]
ругалась что не может установить:
`- libpng12-dev
`
поискал в инете получил ответ что libpng12-dev удалили на данный момент актуальна libpng-dev, изменил все заработало, думаю стоит обновить эту строку на Dockerfile 
`- libpng12-dev`
`- libpng-dev`

**Comment by TheArdent** [comment]
Updated and fixed.
